#!/usr/bin/python3

import os
import sys
import cgi
from art import *

# Récupérer les données POST
form = cgi.FieldStorage()
text = form.getvalue("text")
# if not isinstance(text, str):
#     text = str(text)

# Si aucune donnée POST n'a été envoyée, afficher le formulaire
if not text:
    print("Content-Type: text/html")
    print("")
    print("<!DOCTYPE html>")
    print("<html>")
    print("<head>")
    print("<meta charset='UTF-8'>")
    print("<title>Python Art Page</title>")
    print("<style>")
    print("pre {font-family: monospace;}")
    print("body {")
    print("    background-color: #f1d55a;")
    print("    margin: 0;")
    print("    padding: 0;")
    print("}")
    print("")
    print("header {")
    print("    position: fixed;")
    print("    top: 0;")
    print("    left: 0;")
    print("    right: 0;")
    print("    z-index: 999;")
    print("    background-color: #f1d55a;")
    print("    text-align: center;")
    print("    font-size: 2em;")
    print("    font-weight: bold;")
    print("    box-shadow: 0px 2px 5px rgba(255, 255, 255, 0.3);")
    print("}")
    print("")
    print('header a {')
    print('    color: white;')
    print('    width: 100%;')
    print('    height: 100%;')
    print('    padding: 10px 0;')
    print('    display: block;')
    print('    text-decoration: none;')
    print('}')
    print("")
    print("footer {")
    print("    position: fixed;")
    print("    bottom: 0;")
    print("    left: 0;")
    print("    right: 0;")
    print("    background-color: #111;")
    print("    color: white;")
    print("    text-align: center;")
    print("    padding: 10px 0;")
    print("    font-size: 0.8em;")
    print("}")
    print("")
    print("main {")
    print('    margin-top: 62px;')
    print("    padding-bottom: 60px;")
    print("}")
    print("</style>")
    print("</head>")
    print("<body>")
    print("<header>")
    print("<a href='/index.html'>WebServ</a>")
    print("</header>")
    print("<main>")
    print("<p>Saisissez une chaîne de caractères :</p>")
    print("<form method='post'>")
    print("<input type='text' name='text'>")
    print("<input type='submit' value='Valider'>")
    print("</form>")
    print("</main>")
    print("<footer>🐑 Site web créé par Nicolas, Mathieu et Cyril 🐑</footer>")
    print("</body>")
    print("</html>")
else:
    # Afficher le texte en mode text2art
    Art = text2art(text, font='block', chr_ignore=True)
    print("Content-Type: text/html")
    print("")
    print("<!DOCTYPE html>")
    print("<html>")
    print("<head>")
    print("<meta charset='UTF-8'>")
    print("<title>Python Art Page</title>")
    print("<style>")
    print("pre {font-family: monospace;}")
    print("body {")
    print("    background-color: #f1d55a;")
    print("    margin: 0;")
    print("    padding: 0;")
    print("}")
    print("")
    print("header {")
    print("    position: fixed;")
    print("    top: 0;")
    print("    left: 0;")
    print("    right: 0;")
    print("    z-index: 999;")
    print("    background-color: #f1d55a;")
    print("    text-align: center;")
    print("    font-size: 2em;")
    print("    font-weight: bold;")
    print("    box-shadow: 0px 2px 5px rgba(255, 255, 255, 0.3);")
    print("}")
    print("")
    print('header a {')
    print('    color: white;')
    print('    width: 100%;')
    print('    height: 100%;')
    print('    padding: 10px 0;')
    print('    display: block;')
    print('    text-decoration: none;')
    print('}')
    print("")
    print("footer {")
    print("    position: fixed;")
    print("    bottom: 0;")
    print("    left: 0;")
    print("    right: 0;")
    print("    background-color: #111;")
    print("    color: white;")
    print("    text-align: center;")
    print("    padding: 10px 0;")
    print("    font-size: 0.8em;")
    print("}")
    print("")
    print("main {")
    print('    margin-top: 62px;')
    print("    padding-bottom: 60px;")
    print("}")
    print("</style>")
    print("</head>")
    print("<body>")
    print("<header>")
    print("<a href='/index.html'>WebServ</a>")
    print("</header>")
    print("<main>")
    print("<p>Voici votre texte en mode text2art :</p>")
    print("<pre>")
    print(Art)
    print("</pre>")
    print("</main>")
    print("<p><a href='part.py'>Retour</a></p>")
    print("<footer>🐑 Site web créé par Nicolas, Mathieu et Cyril 🐑</footer>")
    print("</body>")
    print("</html>")