#!/usr/bin/python3
print("Content-Type: text/html\n\n")
print("<html>")
print("<head>")
print("<meta charset='utf-8'>")
print("<title>Test de page Python</title>")
print("</head>")
print("<body>")
print("<h1>Ceci est une page générée en utilisant Python!</h1>")
print("</body>")
print("</html>")